language: php
sudo: false

services:
  - mysql

env:
  global:
    - SS_ENVIRONMENT_TYPE="dev"
    - DB=MYSQL

matrix:
  include:
    - php: 7.2
      env:
        - PHPCS_TEST=1
        - PHPUNIT_TEST=1
    - php: 7.4
      env:
        - PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - composer self-update --2 || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  # Install composer dependencies
  - composer validate
  - composer update

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
